### ISSUE TITLE
graph_def.ParseFromString(file_handle.read()),error UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 77: invalid continuation byte

### ISSUE THREAD

**Issue by mmcuavqgc** [computervisioneng/object-tracking-yolov8-deep-sort#2]
video path and out path .\data\people.mp4 .\out.mp4
2023-03-06 19:00:22.905833: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "F:\object-tracking-yolov8-deep-sort-master\main.py", line 22, in <module>
    tracker = Tracker()
  File "F:\object-tracking-yolov8-deep-sort-master\tracker.py", line 21, in __init__
    self.encoder = gdet.create_box_encoder(encoder_model_filename, batch_size=1)
  File "F:\object-tracking-yolov8-deep-sort-master\deep_sort\tools\generate_detections.py", line 100, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "F:\object-tracking-yolov8-deep-sort-master\deep_sort\tools\generate_detections.py", line 78, in __init__
    graph_def.ParseFromString(file_handle.read())
  File "D:\Users\liush\Anaconda3\envs\yolov8\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "D:\Users\liush\Anaconda3\envs\yolov8\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 77, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 77: invalid continuation byte

**Comment by Dipankar1997161** [comment]
The following error occurred due to an incorrect encoding format.

I believe it is not able to decode the path you have specified. Try getting the output in the same directory and also try providing the input from the root itself to see if the error still exists.

if possible, share the snippet of code that you used with the paths. Maybe I can try

**Comment by mmcuavqgc** [comment]
> The following error occurred due to an incorrect encoding format.
> 
> I believe it is not able to decode the path you have specified. Try getting the output in the same directory and also try providing the input from the root itself to see if the error still exists.
> 
> if possible, share the snippet of code that you used with the paths. Maybe I can try

![image](https://user-images.githubusercontent.com/53895729/226254153-75ca0425-1d3a-4cf5-9372-dd9cf734d054.png)
"I didn't change the code,",
There is ultralytics under the path D: Users life Anaconda3 envs , and the default system call is the path D: Users life Anaconda3 envs
